[package]
version = "0.1.0"
name = "appleproof-program"
edition = "2021"

[dependencies]
alloy-sol-types = { workspace = true }
sp1-zkvm = {version="5.0.0", features=["embedded"]}
appleproof-lib = { path = "../lib" }